id: statistics_popular_block_settings
label: Statistics popular block configuration
migration_tags:
  - Drupal 6
  - Drupal 7
source:
  plugin: variable
  variables:
    - statistics_block_top_day_num
    - statistics_block_top_all_num
    - statistics_block_top_last_num
process:
  top_day_num: statistics_block_top_day_num
  top_all_num: statistics_block_top_all_num
  top_last_num: statistics_block_top_last_num
destination:
  plugin: config
  config_name: block.settings.statistics_popular_block
