# Schema for the configuration files of the Custom Block module.

custom_block.type.*:
  type: config_entity
  label: 'Custom block type settings'
  mapping:
    revision:
      type: integer
      label: 'Create new revision'
    description:
      type: text
      label: 'Description'
