id: stark.online
label: 'Who''s online'
plugin: user_online_block
settings:
  properties:
    administrative: '1'
  seconds_online: '900'
  max_list_count: '10'
  cache: '-1'
status: '1'
label: 'Who''s online'
visibility:
  path:
    visibility: '0'
    pages: ''
  role:
    roles: {  }
  node_type:
    types:
      article: '0'
      page: '0'
      poll: '0'
  visibility__active_tab: edit-visibility-path
module: user
region: sidebar_first
weight: '0'
langcode: und
