# Schema for the configuration files of the Block module.

block.block.*:
  type: config_entity
  label: 'Block'
  mapping:
    theme:
      type: string
      label: 'Theme'
    region:
      type: string
      label: 'Region'
    weight:
      type: integer
      label: 'Weight'
    provider:
      type: string
      label: 'Provider'
    visibility:
      type: mapping
      label: 'Visibility settings'
      mapping:
        path:
          type: mapping
          label: 'Pages'
          mapping:
            visibility:
              type: integer
              label: 'Visibility'
            pages:
              type: string
              label: 'Show block on specific pages'
        role:
          type: mapping
          label: 'Roles'
          mapping:
            roles:
              type: sequence
              label: 'Show block for specific roles'
              sequence:
                - type: string
                  label: 'Role'
        node_type:
          type: mapping
          label: 'Content types'
          mapping:
            types:
              type: sequence
              label: 'Show block for specific content types'
              sequence:
               - type: string
                 label: 'Node type'
    plugin:
      type: string
      label: 'Plugin'
    settings:
      type: block.settings.[%parent.plugin]

block.settings.*:
  type: block_settings
