base_table: forum_index
core: 8.x
description: 'A list of new or active forum topics'
status: '1'
display:
  block_1:
    display_plugin: block
    id: block_1
    display_title: 'Active forum topics'
    position: '1'
    display_options:
      display_description: 'Displays a list of active forum topics'
      sorts:
        last_comment_timestamp:
          id: last_comment_timestamp
          table: forum_index
          field: last_comment_timestamp
          relationship: none
          group_type: group
          admin_label: ''
          order: DESC
          exposed: '0'
          expose:
            label: ''
          granularity: second
          plugin_id: date
      defaults:
        sorts: '0'
        title: '0'
      block_description: 'Active forum topics'
      title: 'Active forum topics'
      link_url: /forum
  default:
    display_plugin: default
    id: default
    display_title: Master
    position: '1'
    display_options:
      access:
        type: none
        options: {  }
      cache:
        type: none
        options: {  }
      query:
        type: views_query
        options:
          disable_sql_rewrite: '0'
          distinct: '0'
          slave: '0'
          query_comment: ''
          query_tags: {  }
      exposed_form:
        type: basic
        options:
          submit_button: Apply
          reset_button: '0'
          reset_button_label: Reset
          exposed_sorts_label: 'Sort by'
          expose_sort_order: '1'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        type: some
        options:
          items_per_page: '5'
          offset: '0'
      style:
        type: html_list
        options:
          grouping: {  }
          row_class: ''
          default_row_class: '1'
          row_class_special: '1'
          type: ul
          wrapper_class: item-list
          class: ''
      row:
        type: fields
      fields:
        nid:
          id: nid
          table: forum_index
          field: nid
          relationship: none
          group_type: group
          admin_label: ''
          label: ''
          exclude: '1'
          alter:
            alter_text: '0'
            text: ''
            make_link: '0'
            path: ''
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '0'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          set_precision: '0'
          precision: '0'
          decimal: .
          separator: ','
          format_plural: '0'
          format_plural_singular: '1'
          format_plural_plural: '@count'
          prefix: ''
          suffix: ''
        title:
          id: title
          table: forum_index
          field: title
          relationship: none
          group_type: group
          admin_label: ''
          label: ''
          exclude: '0'
          alter:
            alter_text: '0'
            text: ''
            make_link: '1'
            path: 'node/[nid]'
            absolute: '0'
            external: '0'
            replace_spaces: '0'
            path_case: none
            trim_whitespace: '0'
            alt: ''
            rel: ''
            link_class: ''
            prefix: ''
            suffix: ''
            target: ''
            nl2br: '0'
            max_length: ''
            word_boundary: '1'
            ellipsis: '1'
            more_link: '0'
            more_link_text: ''
            more_link_path: ''
            strip_tags: '0'
            trim: '0'
            preserve_tags: ''
            html: '0'
          element_type: ''
          element_class: ''
          element_label_type: ''
          element_label_class: ''
          element_label_colon: '0'
          element_wrapper_type: ''
          element_wrapper_class: ''
          element_default_classes: '1'
          empty: ''
          hide_empty: '0'
          empty_zero: '0'
          hide_alter_empty: '1'
          plugin_id: standard
      filters: {  }
      sorts: {  }
      title: 'New forum Topics'
      header: {  }
      footer: {  }
      empty: {  }
      relationships: {  }
      arguments: {  }
      use_more: '1'
      use_more_always: '1'
      use_more_text: More
      link_display: custom_url
  block_2:
    display_plugin: block
    id: block_2
    display_title: 'New forum topics'
    position: '1'
    display_options:
      display_description: 'Displays a list of new forum topics'
      sorts:
        created:
          id: created
          table: forum_index
          field: created
          relationship: none
          group_type: group
          admin_label: ''
          order: DESC
          exposed: '0'
          expose:
            label: ''
          granularity: second
          plugin_id: date
      defaults:
        sorts: '0'
      block_description: 'New forum topics'
      link_url: /forum
label: 'Forum Topic Lists'
module: views
id: forum_topic_lists
tag: 'default'
uuid: e9169074-fc80-4676-9708-8b0ef31c4c69
langcode: en
