# Schema for configuration files of the Field module.

field.settings:
  type: mapping
  label: 'Field settings'
  mapping:
    default_storage:
      type: string
      label: 'The default storage backend for a field'
    language_fallback:
      type: boolean
      label: 'Whether the field display falls back to global language fallback configuration'
    purge_batch_size:
      type: integer
      label: 'Maximum number of field data records to purge'
