config.sync:
  path: '/admin/config/development/configuration'
  defaults:
    _form: '\Drupal\config\Form\ConfigSync'
    _title: 'Synchronize'
  requirements:
    _permission: 'synchronize configuration'

config.diff:
  path: '/admin/config/development/configuration/sync/diff/{config_file}'
  defaults:
    _content: '\Drupal\config\Controller\ConfigController::diff'
  requirements:
    _permission: 'synchronize configuration'

config_export_download:
  path: '/admin/config/development/configuration/export-download'
  defaults:
    _controller: '\Drupal\config\Controller\ConfigController::downloadExport'
  requirements:
    _permission: 'export configuration'

config.export:
  path: '/admin/config/development/configuration/export'
  defaults:
    _form: '\Drupal\config\Form\ConfigExportForm'
    _title: 'Export'
  requirements:
    _permission: 'export configuration'

config.import:
  path: '/admin/config/development/configuration/import'
  defaults:
    _form: '\Drupal\config\Form\ConfigImportForm'
    _title: 'Import'
  requirements:
    _permission: 'import configuration'
