services:
  # @todo: Move this back to core services in #2991683
  config.import_transformer:
    class: Drupal\config_environment\Core\Config\ImportStorageTransformer
    arguments: ['@event_dispatcher', '@database', '@lock', '@lock.persistent']
  config.storage.export:
    class: Drupal\config_environment\Core\Config\ManagedStorage
    arguments: ['@config.storage.export.manager']
  config.storage.export.manager:
    class: Drupal\config_environment\Core\Config\ExportStorageManager
    arguments: ['@config.storage', '@database', '@event_dispatcher', '@lock']
  # config_environment services.
  config_environment.excluded_modules.event_subscriber:
    class: Drupal\config_environment\EventSubscriber\ExcludedModulesEventSubscriber
    arguments: ['@config.storage', '@settings', '@config.manager']
    tags:
      - { name: event_subscriber }
