services:
  # @todo: Move this back to core services in #2991683
  config.import_transformer:
    class: Drupal\config_environment\Core\Config\ImportStorageTransformer
    arguments: ['@event_dispatcher', '@database']
  config.storage.export:
    class: Drupal\config_environment\Core\Config\ManagedStorage
    arguments: ['@config.storage.export.manager']
  config.storage.export.manager:
    class: Drupal\config_environment\Core\Config\ExportStorageManager
    arguments: ['@config.storage', '@state', '@database', '@event_dispatcher']
    tags:
      - { name: event_subscriber }
  # config_environment services.
  config_environment.excluded_modules.event_subscriber:
    class: Drupal\config_environment\EventSubscriber\ExcludedModulesEventSubscriber
    arguments: ['@config.storage', '@settings', '@config.manager', '@state']
    tags:
      - { name: event_subscriber }
