# @todo: Stop taking over config module routes in #2991683
config.sync:
  path: '/admin/config/development/configuration'
  defaults:
    _form: '\Drupal\config_environment\Form\ConfigSync'
    _title: 'Synchronize'
  requirements:
    _permission: 'synchronize configuration'

config.diff:
  path: '/admin/config/development/configuration/sync/diff/{source_name}/{target_name}'
  defaults:
    _controller: '\Drupal\config_environment\Controller\ConfigController::diff'
    target_name: NULL
  requirements:
    _permission: 'synchronize configuration'

config.diff_collection:
  path: '/admin/config/development/configuration/sync/diff_collection/{collection}/{source_name}/{target_name}'
  defaults:
    _controller: '\Drupal\config_environment\Controller\ConfigController::diff'
    target_name: NULL
  requirements:
    _permission: 'synchronize configuration'

config.export_download:
  path: '/admin/config/development/configuration/full/export-download'
  defaults:
    _controller: '\Drupal\config_environment\Controller\ConfigController::downloadExport'
  requirements:
    _permission: 'export configuration'
